spring.application.name=picpaysimplificado

# Configuração do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:picpaydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o Console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Exibe as consultas SQL geradas no console do IntelliJ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true